apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: prod-monitoring-cluster
  region: us-east-1

nodeGroups:
  - name: standard-workers
    instanceType: t3.small
    minSize: 2
    maxSize: 4
    desiredCapacity: 2
    volumeSize: 20
    ssh:
      allow: true
